/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudyRouteImport } from './routes/study'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as ImportGarminRouteImport } from './routes/import-garmin'
import { Route as GarminTrainingsRouteImport } from './routes/garmin-trainings'
import { Route as GarminSleepRouteImport } from './routes/garmin-sleep'
import { Route as ConteudoProgramaticoRouteImport } from './routes/conteudo-programatico'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportGarminRoute = ImportGarminRouteImport.update({
  id: '/import-garmin',
  path: '/import-garmin',
  getParentRoute: () => rootRouteImport,
} as any)
const GarminTrainingsRoute = GarminTrainingsRouteImport.update({
  id: '/garmin-trainings',
  path: '/garmin-trainings',
  getParentRoute: () => rootRouteImport,
} as any)
const GarminSleepRoute = GarminSleepRouteImport.update({
  id: '/garmin-sleep',
  path: '/garmin-sleep',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudoProgramaticoRoute = ConteudoProgramaticoRouteImport.update({
  id: '/conteudo-programatico',
  path: '/conteudo-programatico',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRoute
  '/checkin': typeof CheckinRoute
  '/conteudo-programatico': typeof ConteudoProgramaticoRoute
  '/garmin-sleep': typeof GarminSleepRoute
  '/garmin-trainings': typeof GarminTrainingsRoute
  '/import-garmin': typeof ImportGarminRoute
  '/mapa': typeof MapaRoute
  '/plan': typeof PlanRoute
  '/review': typeof ReviewRoute
  '/study': typeof StudyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRoute
  '/checkin': typeof CheckinRoute
  '/conteudo-programatico': typeof ConteudoProgramaticoRoute
  '/garmin-sleep': typeof GarminSleepRoute
  '/garmin-trainings': typeof GarminTrainingsRoute
  '/import-garmin': typeof ImportGarminRoute
  '/mapa': typeof MapaRoute
  '/plan': typeof PlanRoute
  '/review': typeof ReviewRoute
  '/study': typeof StudyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRoute
  '/checkin': typeof CheckinRoute
  '/conteudo-programatico': typeof ConteudoProgramaticoRoute
  '/garmin-sleep': typeof GarminSleepRoute
  '/garmin-trainings': typeof GarminTrainingsRoute
  '/import-garmin': typeof ImportGarminRoute
  '/mapa': typeof MapaRoute
  '/plan': typeof PlanRoute
  '/review': typeof ReviewRoute
  '/study': typeof StudyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/biblioteca'
    | '/checkin'
    | '/conteudo-programatico'
    | '/garmin-sleep'
    | '/garmin-trainings'
    | '/import-garmin'
    | '/mapa'
    | '/plan'
    | '/review'
    | '/study'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/biblioteca'
    | '/checkin'
    | '/conteudo-programatico'
    | '/garmin-sleep'
    | '/garmin-trainings'
    | '/import-garmin'
    | '/mapa'
    | '/plan'
    | '/review'
    | '/study'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/biblioteca'
    | '/checkin'
    | '/conteudo-programatico'
    | '/garmin-sleep'
    | '/garmin-trainings'
    | '/import-garmin'
    | '/mapa'
    | '/plan'
    | '/review'
    | '/study'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BibliotecaRoute: typeof BibliotecaRoute
  CheckinRoute: typeof CheckinRoute
  ConteudoProgramaticoRoute: typeof ConteudoProgramaticoRoute
  GarminSleepRoute: typeof GarminSleepRoute
  GarminTrainingsRoute: typeof GarminTrainingsRoute
  ImportGarminRoute: typeof ImportGarminRoute
  MapaRoute: typeof MapaRoute
  PlanRoute: typeof PlanRoute
  ReviewRoute: typeof ReviewRoute
  StudyRoute: typeof StudyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-garmin': {
      id: '/import-garmin'
      path: '/import-garmin'
      fullPath: '/import-garmin'
      preLoaderRoute: typeof ImportGarminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garmin-trainings': {
      id: '/garmin-trainings'
      path: '/garmin-trainings'
      fullPath: '/garmin-trainings'
      preLoaderRoute: typeof GarminTrainingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garmin-sleep': {
      id: '/garmin-sleep'
      path: '/garmin-sleep'
      fullPath: '/garmin-sleep'
      preLoaderRoute: typeof GarminSleepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudo-programatico': {
      id: '/conteudo-programatico'
      path: '/conteudo-programatico'
      fullPath: '/conteudo-programatico'
      preLoaderRoute: typeof ConteudoProgramaticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BibliotecaRoute: BibliotecaRoute,
  CheckinRoute: CheckinRoute,
  ConteudoProgramaticoRoute: ConteudoProgramaticoRoute,
  GarminSleepRoute: GarminSleepRoute,
  GarminTrainingsRoute: GarminTrainingsRoute,
  ImportGarminRoute: ImportGarminRoute,
  MapaRoute: MapaRoute,
  PlanRoute: PlanRoute,
  ReviewRoute: ReviewRoute,
  StudyRoute: StudyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
