/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudyRouteImport } from './routes/study'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ImportGarminRouteImport } from './routes/import-garmin'
import { Route as GarminSleepRouteImport } from './routes/garmin-sleep'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportGarminRoute = ImportGarminRouteImport.update({
  id: '/import-garmin',
  path: '/import-garmin',
  getParentRoute: () => rootRouteImport,
} as any)
const GarminSleepRoute = GarminSleepRouteImport.update({
  id: '/garmin-sleep',
  path: '/garmin-sleep',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkin': typeof CheckinRoute
  '/garmin-sleep': typeof GarminSleepRoute
  '/import-garmin': typeof ImportGarminRoute
  '/review': typeof ReviewRoute
  '/study': typeof StudyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkin': typeof CheckinRoute
  '/garmin-sleep': typeof GarminSleepRoute
  '/import-garmin': typeof ImportGarminRoute
  '/review': typeof ReviewRoute
  '/study': typeof StudyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkin': typeof CheckinRoute
  '/garmin-sleep': typeof GarminSleepRoute
  '/import-garmin': typeof ImportGarminRoute
  '/review': typeof ReviewRoute
  '/study': typeof StudyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/checkin'
    | '/garmin-sleep'
    | '/import-garmin'
    | '/review'
    | '/study'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/checkin'
    | '/garmin-sleep'
    | '/import-garmin'
    | '/review'
    | '/study'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/checkin'
    | '/garmin-sleep'
    | '/import-garmin'
    | '/review'
    | '/study'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CheckinRoute: typeof CheckinRoute
  GarminSleepRoute: typeof GarminSleepRoute
  ImportGarminRoute: typeof ImportGarminRoute
  ReviewRoute: typeof ReviewRoute
  StudyRoute: typeof StudyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-garmin': {
      id: '/import-garmin'
      path: '/import-garmin'
      fullPath: '/import-garmin'
      preLoaderRoute: typeof ImportGarminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garmin-sleep': {
      id: '/garmin-sleep'
      path: '/garmin-sleep'
      fullPath: '/garmin-sleep'
      preLoaderRoute: typeof GarminSleepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CheckinRoute: CheckinRoute,
  GarminSleepRoute: GarminSleepRoute,
  ImportGarminRoute: ImportGarminRoute,
  ReviewRoute: ReviewRoute,
  StudyRoute: StudyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
